###NLP EXAMPLES

In [ ]:
from textblob import Word
w = Word('dogs')
w.singularize()

'dog'

In [ ]:
Word('patterns').singularize()

'pattern'

In [ ]:
Word('men').singularize()

'man'

In [ ]:
import pandas as pd
df=pd.DataFrame({"org_name":["ABC consultants pvt ltd","ABC consultant pvt ltd","abc enterprises pvt ltd","abc enterprise pvt ltd"]})
df

                  org_name
0  ABC consultants pvt ltd
1   ABC consultant pvt ltd
2  abc enterprises pvt ltd
3   abc enterprise pvt ltd

In [ ]:
import inflect
p = inflect.engine()
df["rectified_org_name"]=df["org_name"].apply(lambda x:' '.join(map(str,[p.singular_noun(y) if p.singular_noun(y) else y for y in x.split()])))
df

                  org_name      rectified_org_name
0  ABC consultants pvt ltd  ABC consultant pvt ltd
1   ABC consultant pvt ltd  ABC consultant pvt ltd
2  abc enterprises pvt ltd  abc enterprise pvt ltd
3   abc enterprise pvt ltd  abc enterprise pvt ltd

#### Type1

In [ ]:
from textblob import TextBlob

# Define a list of sample texts
texts = [
    "I love this movie, it's fantastic!",
    "This restaurant is terrible, I wouldn't recommend it to anyone.",
    "The weather today is just perfect.",
    "I feel indifferent about this book.",
    "There is a terrorist attack happened in Mumbai.",
    "The customer service was excellent, I'm very satisfied.",
    "Smoking is injurious to health"
]

# Analyze sentiment for each text
for text in texts:
    sentiment_score, subjectivity_score = TextBlob(text).sentiment
    if sentiment_score > 0:
        sentiment_label = "positive"
    elif sentiment_score < 0:
        sentiment_label = "negative"
    else:
        sentiment_label = "neutral"
    print(f"Text: {text}")
    print(f"Sentiment: {sentiment_label}")
    print(f"Sentiment Score: {sentiment_score}")
    print(f"Subjectivity Score: {subjectivity_score}")
"""
Subjective Score:
0: Indicates highly objective text, typically consisting of factual statements, descriptions, or observations that are not influenced by personal feelings or opinions.
1: Indicates highly subjective text, containing personal opinions, emotions, or interpretations.
"""

Text: I love like this movie, it's fantastic!
Sentiment: positive
Sentiment Score: 0.5
Subjectivity Score: 0.75
Text: This restaurant is terrible, I wouldn't recommend it to anyone.
Sentiment: negative
Sentiment Score: -1.0
Subjectivity Score: 1.0
Text: The weather today is just perfect.
Sentiment: positive
Sentiment Score: 1.0
Subjectivity Score: 1.0
Text: I feel indifferent about this book.
Sentiment: neutral
Sentiment Score: 0.0
Subjectivity Score: 0.0
Text: There is a terrorist attack happened in Mumbai.
Sentiment: neutral
Sentiment Score: 0.0
Subjectivity Score: 0.0
Text: The customer service was excellent, I'm very satisfied.
Sentiment: positive
Sentiment Score: 0.825
Subjectivity Score: 1.0
Text: Smoking is injurious to health
Sentiment: neutral
Sentiment Score: 0.0
Subjectivity Score: 0.0

'\nSubjective Score:\n0: Indicates highly objective text, typically consisting of factual statements, descriptions, or observations that are not influenced by personal feelings or opinions.\n1: Indicates highly subjective text, containing personal opinions, emotions, or interpretations.\n'

#### Type2

In [ ]:
pip install flair

Collecting flair
  Downloading flair-0.15.1-py3-none-any.whl.metadata (12 kB)
Collecting boto3>=1.20.27 (from flair)
  Downloading boto3-1.42.59-py3-none-any.whl.metadata (6.7 kB)
Collecting conllu<5.0.0,>=4.0 (from flair)
  Downloading conllu-4.5.3-py2.py3-none-any.whl.metadata (19 kB)
Collecting deprecated>=1.2.13 (from flair)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting ftfy>=6.1.0 (from flair)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: gdown>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from flair) (5.2.1)
Requirement already satisfied: huggingface-hub>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from flair) (1.4.1)
Collecting langdetect>=1.0.9 (from flair)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 25.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: lxml>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from flair) (6.0.2)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib/python3.12/dist-packages (from flair) (3.10.0)
Requirement already satisfied: more-itertools>=8.13.0 in /usr/local/lib/python3.12/dist-packages (from flair) (10.8.0)
Collecting mpld3>=0.3 (from flair)
  Downloading mpld3-0.5.12-py3-none-any.whl.metadata (5.3 kB)
Collecting pptree>=3.1 (from flair)
  Downloading pptree-3.1.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from flair) (2.9.0.post0)
Collecting pytorch-revgrad>=0.2.0 (from flair)
  Downloading pytorch_revgrad-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from flair) (2025.11.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from flair) (1.6.1)
Collecting segtok>=1.5.11 (from flair)
  Downloading segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Collecting sqlitedict>=2.0.0 (from flair)
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tabulate>=0.8.10 in /usr/local/lib/python3.12/dist-packages (from flair) (0.9.0)
Requirement already satisfied: torch>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from flair) (2.10.0+cu128)
Requirement already satisfied: tqdm>=4.63.0 in /usr/local/lib/python3.12/dist-packages (from flair) (4.67.3)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair)
  Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting transformers<5.0.0,>=4.25.0 (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.3 MB/s eta 0:00:00
Collecting wikipedia-api>=0.5.7 (from flair)
  Downloading wikipedia_api-0.9.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting bioc<3.0.0,>=2.0.0 (from flair)
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting jsonlines>=1.2.0 (from bioc<3.0.0,>=2.0.0->flair)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc<3.0.0,>=2.0.0->flair)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting docopt (from bioc<3.0.0,>=2.0.0->flair)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting botocore<1.43.0,>=1.42.59 (from boto3>=1.20.27->flair)
  Downloading botocore-1.42.59-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.20.27->flair)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.20.27->flair)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated>=1.2.13->flair) (2.1.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy>=6.1.0->flair) (0.6.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown>=4.4.0->flair) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown>=4.4.0->flair) (3.24.3)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown>=4.4.0->flair) (2.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair) (4.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect>=1.0.9->flair) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (2.0.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair) (3.3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from mpld3>=0.3->flair) (3.1.6)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.2->flair) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.2->flair) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.2->flair) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.1->flair) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.1->flair) (1.3.5)
Collecting huggingface-hub>=0.10.0 (from flair)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (0.7.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (5.29.6)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.59->boto3>=1.20.27->flair) (2.5.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonlines>=1.2.0->bioc<3.0.0,>=2.0.0->flair) (25.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.1->flair) (1.3.0)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (1.12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown>=4.4.0->flair) (2.8.3)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree->bioc<3.0.0,>=2.0.0->flair) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->mpld3>=0.3->flair) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (2026.1.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (1.7.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0->transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (5.9.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.10.0->flair) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.10.0->flair) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.10.0->flair) (0.16.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.10.0->flair) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.10.0->flair) (0.1.2)
Downloading flair-0.15.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 41.2 MB/s eta 0:00:00
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading boto3-1.42.59-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 17.2 MB/s eta 0:00:00
Downloading conllu-4.5.3-py2.py3-none-any.whl (16 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 6.0 MB/s eta 0:00:00
Downloading mpld3-0.5.12-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.1/203.1 kB 22.1 MB/s eta 0:00:00
Downloading pytorch_revgrad-0.2.0-py3-none-any.whl (4.6 kB)
Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl (14 kB)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 91.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 50.7 MB/s eta 0:00:00
Downloading botocore-1.42.59-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 100.8 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 12.2 MB/s eta 0:00:00
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Building wheels for collected packages: langdetect, pptree, sqlitedict, wikipedia-api, docopt
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=892205c0c720b434e9328cf99dd8047717f2764857f5265fe67983102d7c7605
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
  Building wheel for pptree (setup.py) ... done
  Created wheel for pptree: filename=pptree-3.1-py3-none-any.whl size=4609 sha256=03de5989d224e9c7bfaf59156a15ed7bcc6bb09fc2913f053105d282735b63ac
  Stored in directory: /root/.cache/pip/wheels/b0/2d/de/37058114a8f07cfec75747cb46b864bc5c71b0e9e0e4cd0acd
  Building wheel for sqlitedict (setup.py) ... done
  Created wheel for sqlitedict: filename=sqlitedict-2.1.0-py3-none-any.whl size=16862 sha256=d0d0e772a12c658b7ffbe81be866e15272f494c12be59efde858bf9b1cd9b9b5
  Stored in directory: /root/.cache/pip/wheels/7a/6f/21/fc016aef45ffcabe27129a2252f061387cbf278d2086225a64
  Building wheel for wikipedia-api (setup.py) ... done
  Created wheel for wikipedia-api: filename=Wikipedia_API-0.9.0-py3-none-any.whl size=15422 sha256=a7be61f717baf6d14f31fcd565a5dc9222b6789931283a28a9eb6912c3f87a57
  Stored in directory: /root/.cache/pip/wheels/08/22/bd/5181c75f59d48538eb0c0f3246ac541b8a3f0bce3bfd097047
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=fbdd682c634f6b19cd99abcf6fa67820f958b4790c85121385a4854d01d341d9
  Stored in directory: /root/.cache/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built langdetect pptree sqlitedict wikipedia-api docopt
Installing collected packages: sqlitedict, pptree, docopt, segtok, langdetect, jsonlines, jmespath, intervaltree, ftfy, deprecated, conllu, wikipedia-api, huggingface-hub, botocore, bioc, s3transfer, mpld3, transformers, pytorch-revgrad, boto3, transformer-smaller-training-vocab, flair
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bioc-2.1 boto3-1.42.59 botocore-1.42.59 conllu-4.5.3 deprecated-1.3.1 docopt-0.6.2 flair-0.15.1 ftfy-6.3.1 huggingface-hub-0.36.2 intervaltree-3.2.1 jmespath-1.1.0 jsonlines-4.0.0 langdetect-1.0.9 mpld3-0.5.12 pptree-3.1 pytorch-revgrad-0.2.0 s3transfer-0.16.0 segtok-1.5.11 sqlitedict-2.1.0 transformer-smaller-training-vocab-0.4.2 transformers-4.57.6 wikipedia-api-0.9.0

In [ ]:
# Trained on IMDB ratings that's why this will only give binary response positive/Negative
from flair.models import TextClassifier
from flair.data import Sentence

classifier = TextClassifier.load('sentiment')

texts = [
    "I don't like this movie, it's fantastic!",
    "This restaurant is terrible, I wouldn't recommend it to anyone.",
    "The weather today is just perfect.",
    "I feel indifferent about this book.",
    "There is a terrorist attack happened in Mumbai.",
    "The customer service was excellent, I'm very satisfied.",
    "Smoking is injurious to health"
]

for text in texts:
    sentence = Sentence(text)
    classifier.predict(sentence)
    print(f"Text: {text}")
    print(f"Sentiment: {sentence.labels[0]}")

Text: I don't like this movie, it's fantastic!
Sentiment: Sentence[11]: "I don't like this movie, it's fantastic!" → NEGATIVE (0.9977)
Text: This restaurant is terrible, I wouldn't recommend it to anyone.
Sentiment: Sentence[13]: "This restaurant is terrible, I wouldn't recommend it to anyone." → NEGATIVE (1.0)
Text: The weather today is just perfect.
Sentiment: Sentence[7]: "The weather today is just perfect." → POSITIVE (0.9985)
Text: I feel indifferent about this book.
Sentiment: Sentence[7]: "I feel indifferent about this book." → NEGATIVE (1.0)
Text: There is a terrorist attack happened in Mumbai.
Sentiment: Sentence[9]: "There is a terrorist attack happened in Mumbai." → NEGATIVE (0.973)
Text: The customer service was excellent, I'm very satisfied.
Sentiment: Sentence[11]: "The customer service was excellent, I'm very satisfied." → POSITIVE (0.9829)
Text: Smoking is injurious to health
Sentiment: Sentence[5]: "Smoking is injurious to health" → NEGATIVE (0.8798)

#### Type3

In [ ]:
# Great for tweets, reviews, or short English sentences.
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

texts = [
    "I love this movie, it's fantastic!",
    "This restaurant is terrible, I wouldn't recommend it to anyone.",
    "The weather today is just perfect.",
    "I feel indifferent about this book.",
    "There is a terrorist attack happened in Mumbai.",
    "The customer service was excellent, I'm very satisfied."
]

for text in texts:
    score = sia.polarity_scores(text)
    compound = score['compound']
    sentiment = 'positive' if compound > 0.05 else 'negative' if compound < -0.05 else 'neutral'
    print(f"Text: {text}")
    print(f"Sentiment: {sentiment}, Compound Score: {compound}")

Text: I love this movie, it's fantastic!
Sentiment: positive, Compound Score: 0.8439
Text: This restaurant is terrible, I wouldn't recommend it to anyone.
Sentiment: negative, Compound Score: -0.6381
Text: The weather today is just perfect.
Sentiment: positive, Compound Score: 0.5719
Text: I feel indifferent about this book.
Sentiment: negative, Compound Score: -0.2023
Text: There is a terrorist attack happened in Mumbai.
Sentiment: negative, Compound Score: -0.8316
Text: The customer service was excellent, I'm very satisfied.
Sentiment: positive, Compound Score: 0.7778

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

###LLM:

In [ ]:
!pip install langchain
!pip install ctransformers
!pip install ctransformers[cuda]

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.15)
Requirement already satisfied: langgraph<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.6)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (0.3.9)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.5.0)
Requirement already satisfied: ctransformers in /usr/local/lib/python3.12/dist-packages (0.2.27)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from ctransformers) (1.4.1)
Requirement already satisfied: py-cpuinfo<10.0.0,>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from ctransformers) (9.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub->ctransformers) (0.16.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub->ctransformers) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers) (0.1.2)
Requirement already satisfied: ctransformers[cuda] in /usr/local/lib/python3.12/dist-packages (0.2.27)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from ctransformers[cuda]) (1.4.1)
Requirement already satisfied: py-cpuinfo<10.0.0,>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from ctransformers[cuda]) (9.0.0)
Requirement already satisfied: nvidia-cublas-cu12 in /usr/local/lib/python3.12/dist-packages (from ctransformers[cuda]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in /usr/local/lib/python3.12/dist-packages (from ctransformers[cuda]) (12.8.90)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->ctransformers[cuda]) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers[cuda]) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers[cuda]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers[cuda]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub->ctransformers[cuda]) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub->ctransformers[cuda]) (0.16.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub->ctransformers[cuda]) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub->ctransformers[cuda]) (0.1.2)

In [ ]:
!pip install langchain-community

Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.2.15)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.47)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.6)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.41.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)

In [ ]:
import os
from langchain_community.llms import CTransformers
from langchain_core.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

In [ ]:
model_id = 'TheBloke/Orca-2-13B-GGUF'

In [ ]:
os.environ['XDG_CACHE_HOME'] = 'drive/MyDrive/LLM_data/model/cache/'
config = {'temperature':0.9,'max_new_tokens': 512, 'context_length':4000,'gpu_layers':50,'repetition_penalty':1 }
llm = CTransformers(model=model_id,
                    model_type="llama",
                    gpu_layers=50,
                    device = 0,
                    config=config,
                    callbacks=[StreamingStdOutCallbackHandler()],
                   )

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
llm.invoke('write a short story')

 called 'An Infinite Night'

The sun had set, leaving the sky a dark, inky blue. The stars began to twinkle, and the moon rose, casting a pale light over the land. It was the perfect night for a campout.

The friends had packed their bags and headed to the woods, eager for an adventure. They set up their tents near a bubbling brook and lit a bonfire, sharing stories and laughter late into the night.

As the fire crackled and the stars danced above them, one of the friends noticed something strange. The night seemed to go on forever, and no matter how long they waited, the first light of dawn never came.

The friends began to grow restless and concerned, for their night was now stretching into an infinite darkness. They huddled together, trying to keep warm and find comfort in each other's company.

As the hours dragged on, they started to hear strange sounds. Some were soft and distant, like whispers on the wind. Others were closer, like footsteps on the forest floor. And then there were the unexplainable noises, like the wails of a distant creature, or the rustle of leaves that seemed to move of their own accord.

The friends felt a growing sense of dread, but they couldn't bring themselves to leave their campsite. They were drawn to the mystery of this infinite night, even if it terrified them.

As the darkness deepened, they heard a strange new sound. It was a voice, and it seemed to be calling their names. It was a soft, haunting melody, and it filled the friends with an eerie familiarity. They had heard this voice before, in their dreams or in their memories.

The voice seemed to beckon them, inviting them to follow it into the heart of the darkness. The friends felt a sudden urge to obey, even though they knew it was dangerous.

They left their tents behind and ventured into the woods, guided by the voice. They walked for what felt like hours, until they came to a clearing.

There, they saw an impossibly tall and ancient tree, its branches reaching for the sky. The voice seemed to emanate from this tree, and the friends felt a strange connection to it.

" called 'An Infinite Night'\n\nThe sun had set, leaving the sky a dark, inky blue. The stars began to twinkle, and the moon rose, casting a pale light over the land. It was the perfect night for a campout.\n\nThe friends had packed their bags and headed to the woods, eager for an adventure. They set up their tents near a bubbling brook and lit a bonfire, sharing stories and laughter late into the night.\n\nAs the fire crackled and the stars danced above them, one of the friends noticed something strange. The night seemed to go on forever, and no matter how long they waited, the first light of dawn never came.\n\nThe friends began to grow restless and concerned, for their night was now stretching into an infinite darkness. They huddled together, trying to keep warm and find comfort in each other's company.\n\nAs the hours dragged on, they started to hear strange sounds. Some were soft and distant, like whispers on the wind. Others were closer, like footsteps on the forest floor. And then there were the unexplainable noises, like the wails of a distant creature, or the rustle of leaves that seemed to move of their own accord.\n\nThe friends felt a growing sense of dread, but they couldn't bring themselves to leave their campsite. They were drawn to the mystery of this infinite night, even if it terrified them.\n\nAs the darkness deepened, they heard a strange new sound. It was a voice, and it seemed to be calling their names. It was a soft, haunting melody, and it filled the friends with an eerie familiarity. They had heard this voice before, in their dreams or in their memories.\n\nThe voice seemed to beckon them, inviting them to follow it into the heart of the darkness. The friends felt a sudden urge to obey, even though they knew it was dangerous.\n\nThey left their tents behind and ventured into the woods, guided by the voice. They walked for what felt like hours, until they came to a clearing.\n\nThere, they saw an impossibly tall and ancient tree, its branches reaching for the sky. The voice seemed to emanate from this tree, and the friends felt a strange connection to it."

In [ ]:
llm.invoke("what is cupcake?")

A cupcake is a small cake that is typically baked in a muffin tin or cupcake pan. They are often served as a dessert at parties or celebrations, and can be filled or topped with various flavors and ingredients. Cupcakes can be made with a variety of ingredients, such as cake mix, flour, sugar, eggs, and butter, and can be customized with different flavors, colors, and decorations.

'\nA cupcake is a small cake that is typically baked in a muffin tin or cupcake pan. They are often served as a dessert at parties or celebrations, and can be filled or topped with various flavors and ingredients. Cupcakes can be made with a variety of ingredients, such as cake mix, flour, sugar, eggs, and butter, and can be customized with different flavors, colors, and decorations.'

In [ ]:
llm.invoke("Who is the president of India")

 and which government institutions are under his control?
The president of India is Ram Nath Kovind. The government institutions under his control include the Council of Ministers, the Prime Minister's Office, and the Cabinet Secretariat. The president is also the ceremonial head of the Indian Armed Forces.

" and which government institutions are under his control?\nThe president of India is Ram Nath Kovind. The government institutions under his control include the Council of Ministers, the Prime Minister's Office, and the Cabinet Secretariat. The president is also the ceremonial head of the Indian Armed Forces."

In [ ]:
prompt="what is cupcake?"
prompt1="write a story for me"
response = llm.generate([prompt,prompt1])

A cupcake is a small cake that is typically baked in a cup or muffin-style paper holder. They come in various flavors and decorations and are often served at parties or as a dessert., about a boy who was bullied in school, but found solace in writing, and how his love for writing helped him overcome his fears and insecurities.

Once upon a time, in a small town in the Midwest, there was a boy named Timmy. Timmy was a shy and quiet boy who loved to read and write stories. He spent most of his time in his room, surrounded by books and notebooks, where he could escape from the harsh reality of his life at school.

At school, Timmy was often bullied by his classmates, who taunted him for being weak, stupid, and different. They made fun of his love for books and his dreams of becoming a writer one day. They even went as far as to physically hurt him, leaving him bruised and bleeding.

Despite all of this, Timmy never gave up on his passion for writing. He found solace in the words and stories he created, where he could be whoever he wanted to be. He could be brave, strong, and smart. He could be the hero of his own story.

As Timmy continued to write, he began to notice a change within himself. His confidence grew, and his fears and insecurities began to fade away. He realized that he didn't need to be like the other kids at school, nor did he need their approval. What mattered was his love for writing and the happiness it brought him.

One day, Timmy decided to share one of his stories with his classmates during the school's creative writing session. To his surprise, his classmates were captivated by his story, and for the first time, they treated him with kindness and respect. They even asked him to share more of his stories with them.

Timmy's love for writing had not only helped him overcome his fears and insecurities, but it had also brought him the acceptance and friendship he had always longed for. Through his stories, he had found a way to connect with others and express the true essence of who he was.

And so, Timmy continued to write, growing more confident and skilled with each story he penned. He knew that no matter what challenges life would throw at him, he would always have his love for writing to guide him through the darkest of times.